### ISSUE TITLE
Build Failed On Android

### ISSUE THREAD

**Issue by itsnyx** [IjzerenHein/react-native-shared-element#114]
hi im having build error with yarn android

    "react-native-shared-element": "^0.8.7",
    "react-native": "0.66.5",

output: 

`C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementContent.java:3: error: package android.view does not exist
import android.view.View;
                   ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementContent.java:4: error: package android.graphics does not exist
import android.graphics.RectF;
                       ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementContent.java:5: error: package android.graphics.drawable does not exist
import android.graphics.drawable.Drawable;
                                ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementContent.java:6: error: package android.widget does not exist
import android.widget.ImageView;
                     ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementContent.java:13: error: cannot find symbol
  View view;
  ^
  symbol:   class View
  location: class RNSharedElementContent
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementContent.java:14: error: cannot find symbol
  RectF size;
  ^
  symbol:   class RectF
  location: class RNSharedElementContent
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementContent.java:16: error: cannot find symbol
  static RectF getSize(View view) {
                       ^
  symbol:   class View
  location: class RNSharedElementContent
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementContent.java:16: error: cannot find symbol
  static RectF getSize(View view) {
         ^
  symbol:   class RectF
  location: class RNSharedElementContent
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementDrawable.java:4: error: package android.view does not exist
import android.view.View;
                   ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementDrawable.java:5: error: package android.graphics does not exist
import android.graphics.Rect;
                       ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementDrawable.java:6: error: package android.graphics does not exist
import android.graphics.RectF;
                       ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementDrawable.java:7: error: package android.graphics.drawable does not exist
import android.graphics.drawable.Drawable;
                                ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementDrawable.java:8: error: package android.graphics does not exist
import android.graphics.Canvas;
                       ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementDrawable.java:9: error: package android.graphics does not exist
import android.graphics.Path;
                       ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementDrawable.java:10: error: package android.graphics does not exist
import android.graphics.Outline;
                       ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementDrawable.java:11: error: package android.graphics does not exist
import android.graphics.PixelFormat;
                       ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementDrawable.java:12: error: package android.graphics does not exist
import android.graphics.ColorFilter;
                       ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementDrawable.java:13: error: package android.graphics does not exist
import android.graphics.Matrix;
                       ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementDrawable.java:14: error: package android.widget does not exist
import android.widget.ImageView;
                     ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementDrawable.java:24: error: cannot find symbol
class RNSharedElementDrawable extends Drawable {
                                      ^
  symbol: class Drawable
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:5: error: package android.graphics does not exist
import android.graphics.Color;
                       ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:6: error: package android.graphics does not exist
import android.graphics.Matrix;
                       ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:7: error: package android.view does not exist
import android.view.View;
                   ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:8: error: package android.view does not exist
import android.view.ViewParent;
                   ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:9: error: package android.content does not exist
import android.content.Context;
                      ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementDrawable.java:50: error: cannot find symbol
  private Path mPathForBorderRadiusOutline = null;
          ^
  symbol:   class Path
  location: class RNSharedElementDrawable
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementDrawable.java:128: error: cannot find symbol
  public void setColorFilter(ColorFilter cf) {
                             ^
  symbol:   class ColorFilter
  location: class RNSharedElementDrawable
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementDrawable.java:146: error: cannot find symbol
  public void getOutline(Outline outline) {
                         ^
  symbol:   class Outline
  location: class RNSharedElementDrawable
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementDrawable.java:186: error: cannot find symbol
  static ViewType getViewType(View view, RNSharedElementStyle style) {
                              ^
  symbol:   class View
  location: class RNSharedElementDrawable
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementDrawable.java:206: error: cannot find symbol
  public void draw(Canvas canvas) {
                   ^
  symbol:   class Canvas
  location: class RNSharedElementDrawable
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementDrawable.java:224: error: cannot find symbol
  private void drawReactImageView(Canvas canvas) {
                                  ^
  symbol:   class Canvas
  location: class RNSharedElementDrawable
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementDrawable.java:268: error: cannot find symbol
  private void drawImageView(Canvas canvas) {
                             ^
  symbol:   class Canvas
  location: class RNSharedElementDrawable
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementDrawable.java:293: error: cannot find symbol
  private void drawPlainView(Canvas canvas) {
                             ^
  symbol:   class Canvas
  location: class RNSharedElementDrawable
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementDrawable.java:324: error: cannot find symbol
  private void drawGenericView(Canvas canvas) {
                               ^
  symbol:   class Canvas
  location: class RNSharedElementDrawable
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:22: error: cannot find symbol
  static Rect EMPTY_RECT = new Rect();
         ^
  symbol:   class Rect
  location: class RNSharedElementStyle
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:23: error: cannot find symbol
  static RectF EMPTY_RECTF = new RectF();
         ^
  symbol:   class RectF
  location: class RNSharedElementStyle
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:45: error: cannot find symbol
  RectF layout = new RectF(); // absolute layout on screen
  ^
  symbol:   class RectF
  location: class RNSharedElementStyle
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:46: error: cannot find symbol
  Rect frame = new Rect(); // frame rect relative to parent
  ^
  symbol:   class Rect
  location: class RNSharedElementStyle
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:47: error: cannot find symbol
  RectF ancestorLayout = new RectF(); // absolute layout on screen
  ^
  symbol:   class RectF
  location: class RNSharedElementStyle
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:48: error: cannot find symbol
  Matrix ancestorTransform = new Matrix();
  ^
  symbol:   class Matrix
  location: class RNSharedElementStyle
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:65: error: cannot find symbol
  RNSharedElementStyle(ReadableMap config, Context context) {
                                           ^
  symbol:   class Context
  location: class RNSharedElementStyle
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:152: error: cannot find symbol
  static RectF normalizeLayout(boolean compensateForTransforms, RNSharedElementStyle style, @Size(2) int[] parentOffset) {
         ^
  symbol:   class RectF
  location: class RNSharedElementStyle
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:157: error: cannot find symbol
  static RectF normalizeLayout(boolean compensateForTransforms, RectF layout, RNSharedElementStyle style, @Size(2) int[] parentOffset) {
                                                                ^
  symbol:   class RectF
  location: class RNSharedElementStyle
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:157: error: cannot find symbol
  static RectF normalizeLayout(boolean compensateForTransforms, RectF layout, RNSharedElementStyle style, @Size(2) int[] parentOffset) {
         ^
  symbol:   class RectF
  location: class RNSharedElementStyle
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:181: error: cannot find symbol
  static ScaleType getInterpolatingScaleType(RNSharedElementStyle style1, RectF layout1, RNSharedElementStyle style2, RectF layout2, float position) {
                                                                          ^
  symbol:   class RectF
  location: class RNSharedElementStyle
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:181: error: cannot find symbol
  static ScaleType getInterpolatingScaleType(RNSharedElementStyle style1, RectF layout1, RNSharedElementStyle style2, RectF layout2, float position) {
                                                                                                                      ^
  symbol:   class RectF
  location: class RNSharedElementStyle
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:193: error: cannot find symbol
  static RectF getInterpolatedLayout(RectF layout1, RectF layout2, float position) {
                                     ^
  symbol:   class RectF
  location: class RNSharedElementStyle
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:193: error: cannot find symbol
  static RectF getInterpolatedLayout(RectF layout1, RectF layout2, float position) {
                                                    ^
  symbol:   class RectF
  location: class RNSharedElementStyle
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:193: error: cannot find symbol
  static RectF getInterpolatedLayout(RectF layout1, RectF layout2, float position) {
         ^
  symbol:   class RectF
  location: class RNSharedElementStyle
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:221: error: cannot find symbol
          RectF layout1,
          ^
  symbol:   class RectF
  location: class RNSharedElementStyle
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:223: error: cannot find symbol
          RectF layout2,
          ^
  symbol:   class RectF
  location: class RNSharedElementStyle
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:241: error: cannot find symbol
  static Matrix getAbsoluteViewTransform(View view) {
                                         ^
  symbol:   class View
  location: class RNSharedElementStyle
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:241: error: cannot find symbol
  static Matrix getAbsoluteViewTransform(View view) {
         ^
  symbol:   class Matrix
  location: class RNSharedElementStyle
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:272: error: cannot find symbol
  static float getAncestorVisibility(View view, RNSharedElementStyle style) {
                                     ^
  symbol:   class View
  location: class RNSharedElementStyle
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:283: error: cannot find symbol
  static void getLayoutOnScreen(View view, RectF output)  {
                                ^
  symbol:   class View
  location: class RNSharedElementStyle
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementStyle.java:283: error: cannot find symbol
  static void getLayoutOnScreen(View view, RectF output)  {
                                           ^
  symbol:   class RectF
  location: class RNSharedElementStyle
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNode.java:7: error: package android.os does not exist
import android.os.Handler;
                 ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNode.java:8: error: package android.util does not exist
import android.util.Log;
                   ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNode.java:10: error: package android.view does not exist
import android.view.ViewGroup;
                   ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNode.java:14: error: package android.graphics.drawable does not exist
import android.graphics.drawable.Animatable;
                                ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNode.java:15: error: package android.widget does not exist
import android.widget.ImageView;
                     ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNodeManager.java:15: error: cannot find symbol
  private final Context mContext;
                ^
  symbol:   class Context
  location: class RNSharedElementNodeManager
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNodeManager.java:17: error: cannot find symbol
  RNSharedElementNodeManager(Context context) {
                             ^
  symbol:   class Context
  location: class RNSharedElementNodeManager
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNodeManager.java:29: error: cannot find symbol
  RNSharedElementNode acquire(int reactTag, View view, boolean isParent, View ancestor, ReadableMap styleConfig) {
                                            ^
  symbol:   class View
  location: class RNSharedElementNodeManager
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNodeManager.java:29: error: cannot find symbol
  RNSharedElementNode acquire(int reactTag, View view, boolean isParent, View ancestor, ReadableMap styleConfig) {
                                                                         ^
  symbol:   class View
  location: class RNSharedElementNodeManager
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNode.java:34: error: cannot find symbol
  private final Context mContext;
                ^
  symbol:   class Context
  location: class RNSharedElementNode
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNode.java:36: error: cannot find symbol
  private View mView;
          ^
  symbol:   class View
  location: class RNSharedElementNode
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNode.java:37: error: cannot find symbol
  private View mAncestorView;
          ^
  symbol:   class View
  location: class RNSharedElementNode
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNode.java:41: error: cannot find symbol
  private View mResolvedView;
          ^
  symbol:   class View
  location: class RNSharedElementNode
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNode.java:50: error: cannot find symbol
  private Handler mRetryHandler;
          ^
  symbol:   class Handler
  location: class RNSharedElementNode
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNode.java:52: error: cannot find symbol
  RNSharedElementNode(Context context, int reactTag, View view, boolean isParent, View ancestorView, ReadableMap styleConfig) {
                      ^
  symbol:   class Context
  location: class RNSharedElementNode
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNode.java:52: error: cannot find symbol
  RNSharedElementNode(Context context, int reactTag, View view, boolean isParent, View ancestorView, ReadableMap styleConfig) {
                                                     ^
  symbol:   class View
  location: class RNSharedElementNode
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNode.java:52: error: cannot find symbol
  RNSharedElementNode(Context context, int reactTag, View view, boolean isParent, View ancestorView, ReadableMap styleConfig) {
                                                                                  ^
  symbol:   class View
  location: class RNSharedElementNode
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNode.java:111: error: cannot find symbol
  private static View resolveView(View view, RNSharedElementStyle style) {
                                  ^
  symbol:   class View
  location: class RNSharedElementNode
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNode.java:111: error: cannot find symbol
  private static View resolveView(View view, RNSharedElementStyle style) {
                 ^
  symbol:   class View
  location: class RNSharedElementNode
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNode.java:141: error: cannot find symbol
  View getAncestorView() {
  ^
  symbol:   class View
  location: class RNSharedElementNode
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNode.java:145: error: cannot find symbol
  View getResolvedView() {
  ^
  symbol:   class View
  location: class RNSharedElementNode
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNode.java:302: error: cannot find symbol
  private void addDraweeControllerListener(final View view) {
                                                 ^
  symbol:   class View
  location: class RNSharedElementNode
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementNode.java:336: error: cannot find symbol
  private void removeDraweeControllerListener(final View view) {
                                                    ^
  symbol:   class View
  location: class RNSharedElementNode
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementTransition.java:5: error: package android.annotation does not exist
import android.annotation.SuppressLint;
                         ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementTransition.java:6: error: package android.os does not exist
import android.os.Build;
                 ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementTransition.java:7: error: package android.graphics does not exist
import android.graphics.Canvas;
                       ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementTransition.java:10: error: package android.graphics does not exist
import android.graphics.Color;
                       ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementTransition.java:22: error: cannot find symbol
public class RNSharedElementTransition extends ViewGroup {
                                               ^
  symbol: class ViewGroup
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementTransitionItem.java:5: error: package android.view does not exist
import android.view.ViewParent;
                   ^
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementView.java:10: error: cannot find symbol
class RNSharedElementView extends View {
                                  ^
  symbol: class View
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementTransition.java:140: error: cannot find symbol
  protected void dispatchDraw(Canvas canvas) {
                              ^
  symbol:   class Canvas
  location: class RNSharedElementTransition
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementTransition.java:376: error: cannot find symbol
  static private RectF getClipInsets(RectF layout, RectF clippedLayout) {
                                     ^
  symbol:   class RectF
  location: class RNSharedElementTransition
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementTransition.java:376: error: cannot find symbol
  static private RectF getClipInsets(RectF layout, RectF clippedLayout) {
                                                   ^
  symbol:   class RectF
  location: class RNSharedElementTransition
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementTransition.java:376: error: cannot find symbol
  static private RectF getClipInsets(RectF layout, RectF clippedLayout) {
                 ^
  symbol:   class RectF
  location: class RNSharedElementTransition
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementTransition.java:386: error: cannot find symbol
          RectF interpolatedLayout,
          ^
  symbol:   class RectF
  location: class RNSharedElementTransition
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementTransition.java:387: error: cannot find symbol
          RectF startClipInsets,
          ^
  symbol:   class RectF
  location: class RNSharedElementTransition
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementTransition.java:388: error: cannot find symbol
          RectF startClippedLayout,
          ^
  symbol:   class RectF
  location: class RNSharedElementTransition
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementTransition.java:389: error: cannot find symbol
          RectF endClipInsets,
          ^
  symbol:   class RectF
  location: class RNSharedElementTransition
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementTransition.java:390: error: cannot find symbol
          RectF endClippedLayout,
          ^
  symbol:   class RectF
  location: class RNSharedElementTransition
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementTransition.java:385: error: cannot find symbol
  static private RectF getInterpolatedClipInsets(
                 ^
  symbol:   class RectF
  location: class RNSharedElementTransition
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementTransition.java:433: error: cannot find symbol
  private void fireMeasureEvent(String name, RNSharedElementTransitionItem item, RectF layout, RectF clippedLayout) {
                                                                                 ^
  symbol:   class RectF
  location: class RNSharedElementTransition
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementTransition.java:433: error: cannot find symbol
  private void fireMeasureEvent(String name, RNSharedElementTransitionItem item, RectF layout, RectF clippedLayout) {
                                                                                               ^
  symbol:   class RectF
  location: class RNSharedElementTransition
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementView.java:33: error: cannot find symbol
          RectF layout,
          ^
  symbol:   class RectF
  location: class RNSharedElementView
C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementView.java:34: error: cannot find symbol
          RectF parentLayout,
          ^
  symbol:   class RectF
  location: class RNSharedElementView
Note: C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\react-native-shared-element\android\src\main\java\com\ijzerenhein\sharedelement\RNSharedElementTransition.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
100 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-shared-element:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 45s

    at makeError (C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\execa\index.js:174:9)
    at C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\Users\LEGION\Desktop\Projects\MyApp\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.`

github repo link: 

https://github.com/itsnyx/testAppRepo.git

**Comment by itsnyx** [comment]
i can build with 0.7.0 version !

**Comment by itsnyx** [comment]
also can build with 0.8.4

**Comment by deflexable** [comment]
@itsnyx also having this issue, is there any other solution other than downgrading the version?

**Comment by IjzerenHein** [comment]
I'm looking into it. Seems to have been caused by changes to `build.gradle` in v0.8.6. For now please stick to `v0.8.4`

**Comment by IjzerenHein** [comment]
I've published a new version which fixes the issue:
https://github.com/IjzerenHein/react-native-shared-element/releases/tag/v0.8.8

**Comment by itsnyx** [comment]
thanks for the fast response @IjzerenHein .

**Comment by laurent-kouassi** [comment]
Hi i am having similar issue  please help _> Task :react-native-shared-element:compileReleaseJavaWithJavac FAILED
/Users/laurentkouassi/Desktop/bloom/node_modules/react-native-shared-element/android/src/main/java/com/ijzerenhein/sharedelement/RNSharedElementDrawable.java:18: error: cannot find symbol
import com.facebook.react.views.view.ReactViewBackgroundDrawable;
                                    ^
  symbol:   class ReactViewBackgroundDrawable
  location: package com.facebook.react.views.view
/Users/laurentkouassi/Desktop/bloom/node_modules/react-native-shared-element/android/src/main/java/com/ijzerenhein/sharedelement/RNSharedElementDrawable.java:51: error: cannot find symbol
  private ReactViewBackgroundDrawable mReactViewBackgroundDrawableCache = null;
          ^
  symbol:   class ReactViewBackgroundDrawable
  location: class RNSharedElementDrawable
/Users/laurentkouassi/Desktop/bloom/node_modules/react-native-shared-element/android/src/main/java/com/ijzerenhein/sharedelement/RNSharedElementDrawable.java:297: error: cannot find symbol
    ReactViewBackgroundDrawable drawable = mReactViewBackgroundDrawableCache;
    ^
  symbol:   class ReactViewBackgroundDrawable
  location: class RNSharedElementDrawable
/Users/laurentkouassi/Desktop/bloom/node_modules/react-native-shared-element/android/src/main/java/com/ijzerenhein/sharedelement/RNSharedElementDrawable.java:299: error: cannot find symbol
      drawable = new ReactViewBackgroundDrawable(mContent.view.getContext());
                     ^
  symbol:   class ReactViewBackgroundDrawable
  location: class RNSharedElementDrawable
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
4 errors

_
