### PR TITLE
fix: Implicit conversion of Obj-C pointer type 'UIColor *' to C pointer

### PR DESCRIPTION
**Pull request by lukebars**
With React-Native 0.65.0 RNSharedElement breaks the build, because implicit conversion of Objective-C pointer type 'UIColor *' to C pointer type 'CGColorRef _Nonnull' (aka 'struct CGColor *') requires a bridged cast.

~~This PR fixes it.~~

### CODE REVIEW

**Comment by IjzerenHein** [comment]
Interesting. Looking at the code, it looks like the type was changed from `CGColorRef` to `UIColor *` in react-native 0.65.

```diff
- @property (nonatomic, assign) CGColorRef borderColor;
+ @property (nonatomic, strong) UIColor *borderColor;
```

https://github.com/facebook/react-native/commit/c974cbff04a8d90ac0f856dbada3fc5a75c75b49#diff-48b4675d622955a276e86305c455877e3c53020d28efd6877be4653718591a96R91

**Review by IjzerenHein — CHANGES_REQUESTED** [review]
The suggested change breaks the build on react-native 0.64 and earlier.

image


```
Incompatible types casting 'CGColorRef' (aka 'struct CGColor *') to 'CGColorRef _Nonnull' (aka 'struct CGColor *') with a __bridge cast
```

We'll need a solution that works on older versions as well

**Comment by lukebars** [comment]
@IjzerenHein I had a similar idea, but currently I'm little bit stuck with my solution.

I've also tried yours, it results in:

```
RNSharedElementStyle.m:43:70: implicit conversion of Objective-C pointer type 'UIColor *' to C pointer type 'CGColorRef _Nonnull' (aka 'struct CGColor *') requires a bridged cast
```

**Comment by lukebars** [comment]
@IjzerenHein LGTM, tested on RN65 :shipit:

**Comment by IjzerenHein** [comment]
@lukebars In the mail I got a notification mentioning this:

```
RNSharedElementStyle.m:43:70: implicit conversion of Objective-C pointer type 'UIColor *' to C pointer type 'CGColorRef _Nonnull' (aka 'struct CGColor *') requires a bridged cast
```

Are you running into this problem, or did my solution compile and work correctly on 0.65?

**Comment by lukebars** [comment]
@IjzerenHein I did an human error pasting the code 😄 All is well

**Comment by IjzerenHein** [comment]
@lukebars Awesome :D

**Comment by IjzerenHein** [comment]
Released as 0.8.2:
https://github.com/IjzerenHein/react-native-shared-element/releases/tag/v0.8.2

**Comment by lukebars** [comment]
Thanks!!  🚀
